### ISSUE TITLE
Parallax struggles with theme switching for wallpapers

### ISSUE THREAD

**Issue by toboil-features** [bojidar-bg/plasma-parallax-wallpaper#8]
By using wallpapers which has 2 variations for suiting system theme and changing system theme Parallax doesn't change the wallpaper. 

https://github.com/bojidar-bg/plasma-parallax-wallpaper/assets/160222185/01e5864a-78b4-4f8f-a19f-1a0425be69fa

**Comment by bojidar-bg** [comment]
Should be fixed now. In my defense, it's KDE's MediaProxy doing something funny that confuses the Qt property bindings, and not my code forgetting to listen for palette changes. :sweat_smile:

**Comment by toboil-features** [comment]
Does your commit also fixes accent colors switching? I wish it will be fixed too...

**Comment by toboil-features** [comment]
Built from latest git commit and tried it. The issue is still present.
Also tried the updated version from KDE plugins store, it still there.

KDE Plasma Version: 6.1.2
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.2

**Comment by toboil-features** [comment]
Nevermind, i relogined and now it works. Thanks for the fix. 👍

**Comment by bojidar-bg** [comment]
@toboil-features RE: accent colors -- having tested it, are those still an issue? I might have missed them..
